### ISSUE TITLE
Create encoding-specific conformance classes

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-coverages#166]
This would follow the approach used in OGC API - Features, Tiles, Maps...

Proposed conformance classes:

- CIS JSON
- netCDF
- GeoTIFF
- CoverageJSON

**Comment by pebau** [comment]
@jerstlouis The right hierarchy would be

- CIS
  - JSON
  - RDF
  - netCDF
  - GeoTIFF
  - etc.
- CoverageJSON

**Comment by m-mohr** [comment]
Shouldn't this be extensible? If you prescribe allowed options, what it someone defines COG 2.0?

**Comment by jerstlouis** [comment]
@m-mohr Yes, it is always fully extensible.

As with OGC API - Features, Tiles, EDR and others, even though some conformance classes are defined in the standard itself to facilitate declaring support for common formats, the standard is clear that an HTTP Accept header can always be used to negotiate any other format (and if necessary, a future extension/part to the standard could define a conformance class for those).

**Comment by m-mohr** [comment]
Great to hear. If I can request all file formats through media types (as long as there is one), why do they need conformance classes?

**Comment by jerstlouis** [comment]
@m-mohr For the following reasons:
- Following in the footsteps of Features which had GeoJSON, GML
- To provide a list of formats from which several implementations will at least support one of
- Potentially as a way to procure an implementation that supports at least one or more of those common formats
- As an easy way for clients to know beforehand which formats are available (at least for those common formats) -- related issue: https://github.com/opengeospatial/ogcapi-common/issues/160

**Comment by jerstlouis** [comment]
An initial draft of the encoding-specific requirements classes have been merged with #172.

**Comment by m-mohr** [comment]
So how do I detect a unique list all supported file formats? I'm implementing a client and it must let the user choose the file format he wants to load.

As far as I understand:
1. Get list of conformance classes and filter the file format specific ones out. Q: How do I know which ones are file formats if there can always be non-OGC conformance classes, too?
2. Get all links with a specific rel type and list the media types. Q1: Is there a way to map conformance classes to media types? Q2: What happens if I want to expose STAC JSON and Records JSON, which both currently just use the application/json media type? Q3: What is meant to happen if I find a link without a type property?

**Comment by jerstlouis** [comment]
@m-mohr Tough questions ;) But they apply equally to all OGC API standards, so something to also discuss in _Common_ and/or with the Cross-SWG issue discussions. But trying to answer each point here:

> Q: How do I know which ones are file formats if there can always be non-OGC conformance classes, too?

Not possible for those non-OGC conformance classes in a generic way. Clients that support specific formats can easily identify conformance classes that they recognize whether part of the standard or coming some somewhere else. The reason to include these conformance classes in the first place is to at least have a standard way to identify common formats expected to be supported by several implementations, so at least all clients can recognize these. Generically recognizing conformance classes outside of the standard is not possible.

> Q1: What happens if I want to expose STAC JSON and Records JSON, which both currently just use the application/json media type?

On one hand this could be the general problem that `application/json` is really not an encoding implying a particular logical model, like XML, it's a generic transport for arbitrary logical models, and negotiating a particular profile really needs more information, either using a different media type or with the negotiation by profile ( https://github.com/opengeospatial/ogcapi-common/issues/8 ). In this specific case of STAC vs. Records though it may be related to the question of whether STAC is a profile of records ( has that been resolved in https://github.com/opengeospatial/ogcapi-records/issues/178 ?). Is this related to https://github.com/opengeospatial/ogcapi-records/issues/276 ? I am not clear how any of this relates to _Coverages_ though ? Is this about `/items`?

> Q2: What is meant to happen if I find a link without a type property?

If a link does not include the type property, then the resource likely supports multiple (possibly several) representations, and the client should use an `Accept:` header with those representations that it supports. If this is `/coverage` and the implementation lists those encoding requirements classes in `/conformance`, then the implementation supports all of these. The client should assume that the server does not support those encodings if the requirements classes defined in the standard are not listed.

> I guess the relation types in links take preference over the conformance classes in such a case? Or should they be merged?

Do you mean the `type` and not the `rel` here? The `type` specifies the type for a particular link (e.g., `/coverage?f=coveragejson`), but there should either be no type, or a link of each type listed in the conformance classes. The two should be consistent.

> If yes, is there a way to map conformance classes to media types?

There is a table in the latest draft that does exactly this:

https://github.com/opengeospatial/ogcapi-coverages/blob/master/standard/clause_14_encodings.adoc#media-types

**Comment by m-mohr** [comment]
> Not possible for those non-OGC conformance classes in a generic way.

Okay, so this is not a reliable way to generate a list of supported file formats. Let's look at the other ones then (i.e. the links).

> On one hand this could be the general problem that `application/json` is really not an encoding implying a particular logical model, like XML [...]  I am not clear how any of this relates to _Coverages_ though ? Is this about `/items`?

It was just meant as examples to visualize the issue better. But in principle this can occur for all media types. If I want to support two different flavors of ZARR or netCDF, the same applies basically. I just think that content negotiation by media types (IANA is in priciple relatively strict with "additions" to media types) might get problematic/ambiguous.

> In this specific case of STAC vs. Records though it may be related to the question of whether STAC is a profile of records ( has that been resolved in [opengeospatial/ogcapi-records#178](https://github.com/opengeospatial/ogcapi-records/issues/178) ?). 

STAC will not be a profile of Records in the first iteration, but might be in the future. It is closely aligned but not fully.

> Is this related to [opengeospatial/ogcapi-records#276](https://github.com/opengeospatial/ogcapi-records/issues/276) ?

Yes.

> If a link does not include the type property, then the resource likely supports multiple (possibly several) representations, and the client should use an `Accept:` header with those representations that it supports. If this is `/coverage` and the implementation lists those encoding requirements classes in `/conformance`, then the implementation supports all of these. The client should assume that the server does not support those encodings if the requirements classes defined in the standard are not listed.

So If I write a client such as the GDC Web Editor which let's the choice to the user and in principle supports all media types, what shall I do? I want the user to choose from all supported file formats.

Should I send a `HEAD .../coverage` request and send header `Accept: */*`, but what do I get back then? The Content Type is usually just a single value, not a list, right?


> Do you mean the `type` and not the `rel` here? The `type` specifies the type for a particular link (e.g., `/coverage?f=coveragejson`), but there should either be no type, or a link of each type listed in the conformance classes. The two should be consistent.

I meant if I have a list of supported file formats from the conformance classes and one from the type in the coverage links, which list should I show to users in the GDC Web Editor? I assumed the links have preference, although I can't show a list if there's no type set (see above).

> https://github.com/opengeospatial/ogcapi-coverages/blob/master/standard/clause_14_encodings.adoc#media-types

Good to know, thanks.

**Comment by m-mohr** [comment]
@jerstlouis Copied from another Gitlab issue to have everything in one place:

> Regarding the media type when no type is included, it should be considered multiple, with all of the listed coverage encodings supported as listed in /conformance.

Above, you've said above I can't reliably read that from the conformance classes. So it looks like there is no definitive way to get a list of supported file formats right now, right? This should be fixed, I think.

**Comment by jerstlouis** [comment]
>  Let's look at the other ones then (i.e. the links).

That's not a reliable way either because several implementations may opt to have a single `/coverage` link without a `type`.

**Comment by jerstlouis** [comment]
> So If I write a client such as the GDC Web Editor which let's the choice to the user and in principle supports all media types, what shall I do? I want the user to choose from all supported file formats.

> Should I send a HEAD .../coverage request and send header Accept: */*, but what do I get back then? The Content Type is usually just a single value, not a list, right?

I think this is related to our earlier discussion about at which point you care about which media type to use.
In the end, whether in a particular hop of a workflow, or in the end-user client application, something will need to visualize or analyze that coverage data, and this will support a specific list of formats.

This is where the `Accept: ...` list should ultimately come from, and would never be `*/*`.
In the case of the GDC editor, is there a need to ask the user to pick one?
It may be the list of the formats that the browser supports, or a predetermined list of formats that a particular GDC profile requires to be implemented.

> Otherwise, you/I can't write a user-friendly client.

Just as you said earlier, possibly in a slightly different context:

> the user although they probably don't care which file format is used internally to retrieve the data. They just care what comes out at the end... :-)

> I don't agree with your point that the user needs to specify the file format for the coverage request.

Ideally, I think a user-friendly client should not require the user to deal with formats :)

> I meant if I have a list of supported file formats from the conformance classes and one from the type in the coverage links, which list should I show to users in the GDC Web Editor? I assumed the links have preference, although I can't show a list if there's no type set (see above).

I think the list of supported formats to show would be all of those from the conformance classes, plus any additional conformance classes not in the standard that the client is aware of, plus any `type` ones that are not already mapped to any of these.

>  So it looks like there is no definitive way to get a list of supported file formats right now, right? This should be fixed, I think.

Nothing better than the above, but this applies exactly the same to all OGC API data access standards, including Features.

**Comment by m-mohr** [comment]
> Ideally, I think a user-friendly client should not require the user to deal with formats :)

No! As a user I want to choose whether my end result is a COG or a netCDF. 
In-between the steps/Internally it doesn't care, but the end result I want to choose. And to make an informed decision I need to know upfront which file formats are available. There's no reliable way for this in OGC APIs it seems, so it should be added. Where should such a feature be requested? Here? In Commons?

**Comment by jerstlouis** [comment]
>  As a user I want to choose whether my end result is a COG or a netCDF.

In a connected environment the end-user should not need to care and just see results or get an answer to their question, but this is getting philosophical :) Of course the need for intermediate exports of data still persists, so this is a use case to addres.

>  And to make an informed decision I need to know upfront which file formats are available

As stated above the client can get this right now:
-  all of those from the conformance classes,
- plus any additional conformance classes not in the standard that the client is aware of,
- plus any type ones that are not already mapped to any of these.

This may not seem ideal, but it's not that bad in practice.

If _OGC API - Common - Part 1_ is supported, and the client supports dynamically parsing the particular API definition language used to describe the API (e.g., OpenAPI) for the deployed implementation, then of course the client can also look at the paths responses media types.

> Where should such a feature be requested? Here? In Commons?

This issue https://github.com/opengeospatial/ogcapi-common/issues/160 that I linked to on GitLab is the central place for this discussion I believe. Perhaps optional requirement classes to define requirements for HEAD and/or OPTIONS and/or something similar to the list of media types available in openEO could be a solution? The list of media type would need to be resource type-specific.

**Comment by m-mohr** [comment]
> This may not seem ideal

It is not ideal, it is not reliable and I can't build a client on top of it.

> something similar to the list of media types available in openEO could be a solution? The list of media type would need to be resource type-specific.

openEO defines the file formats globally for input and output respectively. We don't really have different resource types (except for a broad distinction between raster, vector, table and "other",

> https://github.com/opengeospatial/ogcapi-common/issues/160

Thanks, added a short comment there, linking back to this discussion.

**Comment by jerstlouis** [comment]
@m-mohr 
> it is not reliable and I can't build a client on top of it.

The above strategy (standard/client-recognized conformance classes + type) is fully reliable (with the only exception of media types not part of the standard conformance classes and of which the client is not aware), and I think a client can detect / offer that choice, though it might be a bit of work, so it is not clear what you mean by _"I can't build a client on top of it"_.

Are you referring specifically to that exception, do you mean it is significantly more work than it should be, or is there really a technical limitation that I am missing?

> We don't really have different resource types (except for a broad distinction between raster, vector, table and "other",

For OGC APIs, strictly for "data"  we at least havecoverages, maps, feature collections, individual features, vector tiles, coverage tiles, map tiles.

Then there are all the metadata resources like collection lists / collection descriptions, process lists / process descriptions...

**Comment by cnreediii** [comment]
@m-mohr I concur with your statement that the user should be able to 1) get a list of available formats and 2) choose the one they want. Scanning conformance classes to get this information seems overly complex :-)

**Comment by jerstlouis** [comment]
Feb 24 code sprint: do we need a separate conformance class with requirements for GML/JP2 ?

**Comment by m-mohr** [comment]
Here are some more that eventually may need conformance classes: https://gdal.org/en/latest/drivers/raster/index.html
And that's why this doesn't scale well and there needs to be more than just conformance classes for file format discovery.

**Comment by jerstlouis** [comment]
Closing this issue as we've added all planned [encodings requirements classes](https://docs.ogc.org/DRAFTS/19-087.html#encodings-section).

@m-mohr @cnreediii Regarding the content negotiation, there are a number of options:
- List all the encodings in the OpenAPI definitions,
- use different links with `type` media type values
- Supported requirement class declarations (especially for those already defined in the standard -- including the ability to do this per collection),
- Use an `Accept:` response for an OPTIONS method on `/collections/{collectionId}/coverage` (as discussed in https://github.com/opengeospatial/ogcapi-common/issues/160#issuecomment-2945408219)

We could potentially add a recommendation to support this OPTIONS approach in an updated Common - Part 1 as a general recommendation for all OGC APIs, and we could also add it to OGC API - Coverages as well if deemed useful.
